version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=admin123
      - DB_NAME=letscom
    networks:
      - app-network

  db:
    build:
      context: .
      dockerfile: Dockerfile/Dockerfile.mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=letscom
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin123
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data: 