# Use a imagem oficial do MariaDB
FROM mariadb:10.5

# Definir variáveis de ambiente para o MariaDB
ENV MYSQL_ROOT_PASSWORD=admin123
ENV MYSQL_DATABASE=letscom
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=db123

# Expor a porta 3306 para o MariaDB
EXPOSE 3306

# Configurar encoding padrão
CMD ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
